# Generated by Django 3.0 on 2019-12-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20191218_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinfo',
            name='birthday',
            field=models.DateField(default='2006-01-03'),
        ),
        migrations.AddField(
            model_name='getinfo',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='over_18',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='school',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
